(function(m,p,a){function d(a){return this instanceof d?this.map(a):new d(a)}function g(b){return this instanceof g?(this.collection={},this.data=a.isPlainObject(b)?b:{},a.reduce(Object.getPrototypeOf(this),a.bind(function(b,e,f){return a.isFunction(e)?a.set(b,f,a.bind(e,this)):b},this),{})):new g(b)}function h(b,c){return this instanceof h?(c=a.isNil(c)?{}:c,d.switchCase(a.zipObject(h.getNames(),"buildSection buildCustomerInfo buildProducts buildCart buildPurchase buildErrorCheckoutAvailability buildErrorCheckoutSignIn buildErrorPaymentNotAuthorised buildErrorPaymentServerError buildErrorSearchResults buildErrorNoSearchResults buildErrorNoSsluResults".split(" ")),
b,{},a.bind(function(a){return this[a](d(c),c)},this))):new h(b,c)}d.switchCase=function(b,c,e,f){b=a.get(b,c);if(a.isNil(b))return e;a.isFunction(f)&&(b=f(b));return a.isNil(b)?e:b};d.toNumber=function(b){b=a.toNumber(b);return a.isNaN(b)?0:b};d.merge=function(){var b=a.flatten(arguments);b.push(function(b,e){if(a.isArray(e))return e});return a.mergeWith.apply(a,b)};d.prototype.map=function(){var b={},c=a.memoize(function(c){if(a.isArray(c))return a.reduce(c,function(b,c){return a.merge(b,d(c))},
b);if(!a.isPlainObject(c))return b;var f=g(c);f.map("environment","environment",function(b){return a.toLower(b)});f.map("BurberryStore.id","store.country",function(b){b=a.last(a.split(a.toUpper(b),"_"));"UK"===b&&(b="GB");return b});f.map("BurberryStore.BaseCurrencyCode","store.currency",function(b){if("ROW"!==f.get("store.country"))return a.toUpper(b)});f.map("BurberryStore.Language","store.language",function(b){return a.toLower(b)});f.map("soldOut","store.soldOut",function(b){return a.isTruthy(b)});
f.map("BurberryStore.siteError","store.error",function(b){if(a.isString(b)&&a.size(b)&&(b=a.reduce(a.split(b,";"),function(b,c){return a.concat(b,d.switchCase({"checkout.login.invalidPassword":"checkoutSignIn","payment.not.authorised":"paymentNotAuthorised","checkout.generic.billing":"paymentServerError"},c,[]))},[]),a.size(b)))return b});f.map("search.searchKeyWord","search.query");f.map("search.searchResultsCount","search.count",function(a){return d.toNumber(a)});f.map("order.id","cart.id");f.map(["total",
"order.total"],"cart.subTotal",function(a){return d.toNumber(a)});f.map("order.totalPurchaseValue","cart.total",function(a){return d.toNumber(a)});f.map(["counter","order.totalItemCount"],"cart.count",function(a){return d.toNumber(a)});f.map("items","cart.products",function(b){return a.reduce(b,function(b,c){var e=g(c);e.map(["title","productName"],"product.title");e.map(["id","productID"],"product.id");e.map(["categoryId","productCategoryID"],"product.category.id");e.map("available","product.available",
function(b){a.isFalsy(b)&&f.set("cart.available",!1);return b});e.map("sub-total","product.price",function(a){return d.toNumber(a)});e.map("quantity","quantity",function(a){return d.toNumber(a)});return a.concat(b,e.get())},[])});f.map("pagetype","page.root",function(b){return"homepage"===a.toLower(b)});f.map("systemPageType","page.type",function(a){return d.switchCase({categoryLanding:"landing",categoryListing:"listing",categoryListingBeauty:"listing",productDetail:"product",searchResult:"searchResult",
sslu:"storeStock",storeSet:"storeLocator",menuPage:"customerService",basicMenuPage:"customerService",storeDetails:"customerService",contentMenuPage:"customerService",accountLogin:"account",accountCreate:"account",accountOverview:"accountOverview",accountFavourites:"accountFavourites",accountOrderList:"accountOrders",accountOrderDetail:"accountOrders",accountDetails:"accountDetails",accountAddresses:"accountDetails",accountZoozCreditCards:"accountDetails",accountEmailPreferences:"accountDetails",accountEditDetails:"accountDetails",
accountUpdatePassword:"accountDetails",accountEditAddress:"accountDetails",accountAddAddress:"accountDetails",checkoutShoppingBag:"checkoutShoppingBag",checkoutEmail:"checkoutEmail",checkoutDelivery:"checkoutShipping",checkoutPayment:"checkoutPayment",checkoutOrderConfirmation:"checkoutOrderConfirmation"},a,"other")});return f.get()},function(a){return JSON.stringify(a)});return function(a){return b=d.merge({},b,c(a))}}();g.prototype.map=function(b,c,e){a.each(a.castArray(b),a.bind(function(b){b=
d.switchCase(this.data,b,null,e);a.isNull(b)||a.set(this.collection,c,b)},this))};g.prototype.set=function(b,c){c=a.isFunction(c)?c():c;a.isNil(c)||a.set(this.collection,b,c)};g.prototype.get=function(b,c){return a.isString(b)||a.isArray(b)?a.get(this.collection,b,c):this.collection};g.prototype.raw=function(b,c){return a.isString(b)||a.isArray(b)?a.get(this.data,b,c):this.data};h.getNames=function(){return"section ctmrinfo products cart purchase errorCheckoutAvailability errorCheckoutSignIn errorPaymentNotAuthorised errorPaymentServerError errorSearchResults errorNoSearchResults errorNoSsluResults".split(" ")};
h.prototype.buildSection=function(b){var c=g(b);c.map("environment","environment",function(a){return d.switchCase({production:"prod",development:"qa"},a)});c.map("store.language","language");c.set("all","site_all");c.map("page.type","type",function(a){return d.switchCase({landing:"landing",listing:"plp",product:"pdp",searchResult:"search",storeStock:"store_stock_lookup",storeLocator:"store_locator",customerService:"customer_service",account:"my_account",accountOverview:["my_account","my_account_overview"],
accountFavourites:["my_account","my_account_favourites"],accountOrders:["my_account","my_account_orders"],accountDetails:["my_account","my_account_details"],checkoutShoppingBag:["checkout","checkout_bag"],checkoutEmail:["checkout","checkout_sign_in"],checkoutShipping:["checkout","checkout_shipping","checkout_shipping_address","checkout_shipping_option","checkout_packaging_option"],checkoutPayment:["checkout","checkout_payment","checkout_payment_method","checkout_gift_card"],checkoutOrderConfirmation:["checkout",
"checkout_order_confirmation"],other:"other"},a,null,function(a){c.raw("page.root")&&(a="home");"pdp"===a&&c.raw("store.soldOut")&&(a=["pdp","pdp_sold_out"]);"search"===a&&0===c.raw("search.count")&&(a="no_search_results");return a})});return a.chain(c.get()).values().flatten().map(function(b){return a.toUpper("section_"+b)}).value()};h.prototype.buildCustomerInfo=function(a){a=g(a);a.set("type","ctmrinfo");a.map("store.country","info.storeNumber");a.map("cart.subTotal","info.balance");a.map("store.currency",
"info.currency");return a.get()};h.prototype.buildProducts=function(b){b=g(b);b.map("cart.products","products",function(b){return a.map(b,function(a){a=g(a);a.map("product.title","product.name");a.map("product.id","product.sku");a.map("product.category.id","product.category");a.map("product.price","product.price");a.map("quantity","quantity");return a.get()})});return b.get("products")};h.prototype.buildCart=function(a){var c=g(a);c.set("type","cart");c.map("cart.subTotal","total");c.map("store.currency",
"currency");c.map("cart.count","numItems");c.set("products",this.buildProducts(a));return c.get()};h.prototype.buildPurchase=function(a){var c=g(a);c.set("type","purchase");c.map("cart.id","orderId");c.map("cart.total","total");c.map("store.currency","currency");c.map("cart.count","cart.numItems");c.set("cart.products",this.buildProducts(a));return c.get()};h.prototype.buildErrorCheckoutAvailability=function(){return{type:"error",error:{code:"ERR_CHCK_OOS",message:"Some of items in the bag are no longer available."}}};
h.prototype.buildErrorCheckoutSignIn=function(){return{type:"error",error:{code:"ERR_CHCK_SIGN_IN",message:"Invalid username & password combination."}}};h.prototype.buildErrorPaymentNotAuthorised=function(){return{type:"error",error:{code:"ERR_CHCK_CARD_NOT_AUTH",message:"The credit card submitted has not been authorized."}}};h.prototype.buildErrorPaymentServerError=function(){return{type:"error",error:{code:"ERR_CHCK_SYSTEM_ERR",message:"A system error prevented order from completing."}}};h.prototype.buildErrorSearchResults=
function(a){return{type:"error",error:{code:"ERR_SRP",message:'Search results with query: "'+g(a).raw("search.query","")+'".'}}};h.prototype.buildErrorNoSearchResults=function(a){return{type:"error",error:{code:"ERR_NSRP",message:'No search results with query: "'+g(a).raw("search.query","")+'".'}}};h.prototype.buildErrorNoSsluResults=function(a,c){var e=g(c);return{type:"error",error:{code:"ERR_SSLU_NO_RESULTS",message:"No results with id: "+e.raw("productId","")+", size: "+e.raw("productSize","")+
", country: "+e.raw("country","")}}};h.prototype=a.mapValues(h.prototype,function(b){return a.isFunction(b)?a.memoize(b):b});window.lpService=function(b,c){var e=null,f=!1,d=function(){var b=function(){var b={};return{set:function(c,e){a.mergeWith(b,a.set({},c,a.castArray(e)),function(b,c){if(a.isArray(b))return b.concat(c)})},get:function(c,e){return a.get(b,c,e)},unset:function(c,e){var d=this.get(c,e);return a.unset(b,c)?d:!1}}}(),c=function(c,d,f,g){e&&(a.isPlainObject(d)||(d=a.zipObject(["event",
"namespace"],a.split(d,"."))),a.each(a.castArray(f),function(a){d.namespace&&b.set([d.namespace,a],g);e.events.bind({appName:d.event,eventName:a,func:g,triggerOnce:c})}))};return{bind:a.partial(c,!1),once:a.partial(c,!0),unbind:function(c,d){f&&(a.isPlainObject(c)||(c=a.zipObject(["event","namespace"],a.split(c,"."))),a.each(a.castArray(d),function(d){var f=b.unset([c.namespace,d],[]);a.size(f)?a.each(f,function(a){e.events.unbind({appName:c.event,eventName:d,func:a})}):e.events.unbind({appName:c.event,
eventName:d})}))}}}(),h=function(b,c){if(a.isPlainObject(b)&&e){b.context||(b.context=e);var d=a.get(b.context,b.path);d&&a.set(b.context,b.path,function(){d.apply(this,arguments);c.apply(this,arguments)})}},g=function(b,c){a.isFunction(c)&&(c=c());a.isBoolean(c)||(c=!1);var d=document.body.classList;d[c?"add":"remove"].apply(d,a.castArray(b))};return{getState:function(c,d,e){var f=b();d=a.isFunction(d)?d:a.noop;e=a.isFunction(e)?e:a.noop;if(a.isString(c)||a.isArray(c))f=a.get(f,c);a.isNil(f)?e():
d(f);return f},newPage:function(d){f&&(this.pushSection(d),e.newPage(window.location.href,{sdes:a.chain(e.sdes.get()).pick(c.getNames()).mapValues(function(a){return b.merge(a)}).values().value()}))},pushSection:function(a){e&&(e.section=c("section",a))},pushEngagement:function(){var d=[];return function(g,h){var k=a.reduce(a.castArray(g),function(b,c){return a.concat(b,{schema:c,data:h})},[]);f?(d.length&&(k=a.flatten(a.concat(d,k)),d=[]),k=a.mapValues(a.groupBy(k,"schema"),function(d){d=a.map(d,
function(a){return c(a.schema,a.data)});return b.merge(d)}),a.each(k,function(b,c){var d=a.last(e.sdes.get(c));a.isEqual(d,b)||e.sdes.push(b)})):d.push(k)}}(),init:a.once(function(c,l){var n=this;if(e=c)this.pushSection(l),d.once("LPTAG","ON_STARTED",function(){f=!0;n.pushEngagement("ctmrinfo",l);m.core.notify("lpService:start")}),d.once("LP_OFFERS","START",function(){h({path:"taglets.baseOffer.prototype.trigger"},function(c){var e=this;if("OFFER_DISPLAY"===c)if(h({context:this,path:"cleanupOffer"},
function(b){!0===a.get(b,"silent")&&e.trigger("OFFER_REMOVE")}),this.mainContainer.className="lp-overlay-container "+b.switchCase({lpGlobalStickyChatButtonContainer:"lp-sticky-chat-button-overlay-container",lpCheckoutChatButtonContainer:"lp-embedded-chat-button-overlay-container","null":"lp-proactive-message-overlay-container"},e.parentContainer,""),this.mainContainer.tabIndex=-1,this.mainContainer.removeAttribute("style"),this.parentContainer)this.mainContainer.onkeyup=function(a){(13===a.keyCode||
13===a.which)&&(a=this.querySelector("[data-lp-event]"))&&a.focus()},d.bind("lpUnifiedWindow.focus-"+this.parentContainer,["windowClosed","minimized"],function(){e.mainContainer.focus()}),d.bind("lpUnifiedWindow.count-"+this.parentContainer,["maximized","notification"],function(b){b=a.isPlainObject(b)?b:{count:0};g("lp-service-unread-message",function(){return 0<b.count})}),"lpGlobalStickyChatButtonContainer"===this.parentContainer&&g("lp-service-sticky-chat-button",!0);else{var f=document.getElementById("lpGlobalStickyChatButtonContainer");
f&&f.appendChild(this.mainContainer);g("lp-service-proactive-message",!0)}"OFFER_REMOVE"===c&&(this.parentContainer?(d.unbind("lpUnifiedWindow.focus-"+this.parentContainer,["windowClosed","minimized"]),d.unbind("lpUnifiedWindow.count-"+this.parentContainer,["maximized","notification"]),"lpGlobalStickyChatButtonContainer"===this.parentContainer&&g("lp-service-sticky-chat-button",!1)):g("lp-service-proactive-message",!1))})}),d.bind("lpUnifiedWindow","state",function(a){if("init"===a.state&&(a=document.getElementById("lpGlobalStickyChatButtonContainer"))){var b=
document.querySelector('[data-lp-point="minimized"]');b&&(b.className="lp-overlay-container lp-minimized-chat-button-overlay-container",b.tabIndex=0,b.onkeyup=function(a){13!==a.keyCode&&13!==a.which||this.dispatchEvent(new Event("click",{bubbles:!0,cancelable:!0}))},a.appendChild(b),g("lp-service-minimized-chat-button",!0),d.once("lpUnifiedWindow","windowClosed",function(){b.remove();g("lp-service-minimized-chat-button",!1)}))}}),e.start()})}}(d,h);window.lpTag={autoStart:!1}})(window.Ply,window.jQuery,
window._);
