!function(f,g,r){function n(a,b){return typeof a===b}function A(a){var b=m.className,c=d._config.classPrefix||"";if(x&&(b=b.baseVal),d._config.enableJSClass)b=b.replace(new RegExp("(^|\\s)"+c+"no-js(\\s|$)"),"$1"+c+"js$2");d._config.enableClasses&&(b+=" "+c+a.join(" "+c),x?m.className.baseVal=b:m.className=b)}function B(a,b){if("object"==typeof a)for(var c in a)C(a,c)&&B(c,a[c]);else{a=a.toLowerCase();c=a.split(".");var z=d[c[0]];if(2==c.length&&(z=z[c[1]]),"undefined"!=typeof z)return d;b="function"==
typeof b?b():b;1==c.length?d[c[0]]=b:(!d[c[0]]||d[c[0]]instanceof Boolean||(d[c[0]]=new Boolean(d[c[0]])),d[c[0]][c[1]]=b);A([(b&&0!=b?"":"no-")+c.join("-")]);d._trigger(a,b)}return d}function h(){return"function"!=typeof g.createElement?g.createElement(arguments[0]):x?g.createElementNS.call(g,"http://www.w3.org/2000/svg",arguments[0]):g.createElement.apply(g,arguments)}function D(a){return a.replace(/([a-z])-([a-z])/g,function(a,c,d){return c+d.toUpperCase()}).replace(/^-/,"")}function E(a,b,c,d){var p,
f,e,F,k=h("div"),l;e=g.body;l=(e||(e=h(x?"svg":"body"),e.fake=!0),e);if(parseInt(c,10))for(;c--;)e=h("div"),e.id=d?d[c]:"modernizr"+(c+1),k.appendChild(e);return p=h("style"),p.type="text/css",p.id="smodernizr",(l.fake?l:k).appendChild(p),l.appendChild(k),p.styleSheet?p.styleSheet.cssText=a:p.appendChild(g.createTextNode(a)),k.id="modernizr",l.fake&&(l.style.background="",l.style.overflow="hidden",F=m.style.overflow,m.style.overflow="hidden",m.appendChild(l)),f=b(k,a),l.fake?(l.parentNode.removeChild(l),
m.style.overflow=F,m.offsetHeight):k.parentNode.removeChild(k),!!f}function N(a,b){return function(){return a.apply(b,arguments)}}function G(a){return a.replace(/([A-Z])/g,function(a,c){return"-"+c.toLowerCase()}).replace(/^ms-/,"-ms-")}function O(a,b){var c=a.length;if("CSS"in f&&"supports"in f.CSS){for(;c--;)if(f.CSS.supports(G(a[c]),b))return!0;return!1}if("CSSSupportsRule"in f){for(var d=[];c--;)d.push("("+G(a[c])+":"+b+")");return d=d.join(" or "),E("@supports ("+d+") { #modernizr { position: absolute; } }",
function(a){return"absolute"==getComputedStyle(a,null).position})}return r}function P(a,b,c,d){function p(){f&&(delete q.style,delete q.modElem)}if(d=n(d,"undefined")?!1:d,!n(c,"undefined")){var e=O(a,c);if(!n(e,"undefined"))return e}for(var f,g,k,l,e=["modernizr","tspan"];!q.style;)f=!0,q.modElem=h(e.shift()),q.style=q.modElem.style;g=a.length;for(e=0;g>e;e++)if(k=a[e],l=q.style[k],!!~(""+k).indexOf("-")&&(k=D(k)),q.style[k]!==r){if(d||n(c,"undefined"))return p(),"pfx"==b?k:!0;try{q.style[k]=c}catch(m){}if(q.style[k]!=
l)return p(),"pfx"==b?k:!0}return p(),!1}function y(a,b,c,d,e){var f=a.charAt(0).toUpperCase()+a.slice(1),g=(a+" "+H.join(f+" ")+f).split(" "),h;if(n(b,"string")||n(b,"undefined"))h=P(g,b,d,e);else{g=(a+" "+I.join(f+" ")+f).split(" ");a:{a=g;for(var k in a)if(a[k]in b){b=!1===c?a[k]:(h=b[a[k]],n(h,"function")?N(h,c||b):h);break a}b=!1}h=b}return h}function t(a,b,c){return y(a,r,r,b,c)}var J=[],v=[],e={_version:"3.3.1",_config:{classPrefix:"mod_",enableClasses:!0,enableJSClass:!0,usePrefixes:!0},_q:[],
on:function(a,b){var c=this;setTimeout(function(){b(c[a])},0)},addTest:function(a,b,c){v.push({name:a,fn:b,options:c})},addAsyncTest:function(a){v.push({name:null,fn:a})}},d=function(){};d.prototype=e;d=new d;d.addTest("cookies",function(){try{g.cookie="cookietest=1";var a=-1!=g.cookie.indexOf("cookietest=");return g.cookie="cookietest=1; expires=Thu, 01-Jan-1970 00:00:01 GMT",a}catch(b){return!1}});d.addTest("cors","XMLHttpRequest"in f&&"withCredentials"in new XMLHttpRequest);d.addTest("customevent",
"CustomEvent"in f&&"function"==typeof f.CustomEvent);d.addTest("eventlistener","addEventListener"in f);d.addTest("geolocation","geolocation"in navigator);d.addTest("history",function(){var a=navigator.userAgent;return-1===a.indexOf("Android 2.")&&-1===a.indexOf("Android 4.0")||-1===a.indexOf("Mobile Safari")||-1!==a.indexOf("Chrome")||-1!==a.indexOf("Windows Phone")?f.history&&"pushState"in f.history:!1});d.addTest("ie8compat",!f.addEventListener&&!!g.documentMode&&7===g.documentMode);d.addTest("serviceworker",
"serviceWorker"in navigator);d.addTest("websockets","WebSocket"in f&&2===f.WebSocket.CLOSING);d.addTest("xdomainrequest","XDomainRequest"in f);d.addTest("sharedworkers","SharedWorker"in f);d.addTest("webworkers","Worker"in f);var m=g.documentElement;d.addTest("willchange","willChange"in m.style);var x="svg"===m.nodeName.toLowerCase(),I=e._config.usePrefixes?["moz","o","ms","webkit"]:[];e._domPrefixes=I;var C;!function(){var a={}.hasOwnProperty;C=n(a,"undefined")||n(a.call,"undefined")?function(a,
c){return c in a&&n(a.constructor.prototype[c],"undefined")}:function(b,c){return a.call(b,c)}}();e._l={};e.on=function(a,b){this._l[a]||(this._l[a]=[]);this._l[a].push(b);d.hasOwnProperty(a)&&setTimeout(function(){d._trigger(a,d[a])},0)};e._trigger=function(a,b){if(this._l[a]){var c=this._l[a];setTimeout(function(){var a;for(a=0;a<c.length;a++)(0,c[a])(b)},0);delete this._l[a]}};d._q.push(function(){e.addTest=B});d.addTest("audio",function(){var a=h("audio"),b=!1;try{(b=!!a.canPlayType)&&(b=new Boolean(b),
b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"').replace(/^no$/,""),b.mp3=a.canPlayType('audio/mpeg; codecs="mp3"').replace(/^no$/,""),b.opus=a.canPlayType('audio/ogg; codecs="opus"').replace(/^no$/,""),b.wav=a.canPlayType('audio/wav; codecs="1"').replace(/^no$/,""),b.m4a=(a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;")).replace(/^no$/,""))}catch(c){}return b});d.addTest("canvas",function(){var a=h("canvas");return!(!a.getContext||!a.getContext("2d"))});d.addTest("video",function(){var a=
h("video"),b=!1;try{(b=!!a.canPlayType)&&(b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"').replace(/^no$/,""),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"').replace(/^no$/,""),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/^no$/,""),b.vp9=a.canPlayType('video/webm; codecs="vp9"').replace(/^no$/,""),b.hls=a.canPlayType('application/x-mpegURL; codecs="avc1.42E01E"').replace(/^no$/,""))}catch(c){}return b});d.addTest("webanimations","animate"in h("div"));
d.addTest("webgl",function(){var a=h("canvas"),b="probablySupportsContext"in a?"probablySupportsContext":"supportsContext";return b in a?a[b]("webgl")||a[b]("experimental-webgl"):"WebGLRenderingContext"in f});var K=function(){var a=!("onblur"in g.documentElement);return function(b,c){var d;return b?(c&&"string"!=typeof c||(c=h(c||"div")),b="on"+b,d=b in c,!d&&a&&(c.setAttribute||(c=h("div")),c.setAttribute(b,""),d="function"==typeof c[b],c[b]!==r&&(c[b]=r),c.removeAttribute(b)),d):!1}}();e.hasEvent=
K;d.addTest("hashchange",function(){return!1===K("hashchange",f)?!1:g.documentMode===r||7<g.documentMode});var w=e._config.usePrefixes?" -webkit- -moz- -o- -ms- ".split(" "):[];e._prefixes=w;d.addTest("cssgradients",function(){for(var a,b="",c=0,e=w.length-1;e>c;c++)a=0===c?"to ":"",b+="background-image:"+w[c]+"linear-gradient("+a+"left top, #9f9, white);";d._config.usePrefixes&&(b+="background-image:-webkit-gradient(linear,left top,right bottom,from(#9f9),to(white));");a=h("a").style;return a.cssText=
b,-1<(""+a.backgroundImage).indexOf("gradient")});d.addTest("supports","CSS"in f&&"supports"in f.CSS||"supportsCSS"in f);var H=e._config.usePrefixes?["Moz","O","ms","Webkit"]:[];e._cssomPrefixes=H;var L=function(a){var b,c=w.length,d=f.CSSRule;if("undefined"==typeof d)return r;if(!a)return!1;if(a=a.replace(/^@/,""),b=a.replace(/-/g,"_").toUpperCase()+"_RULE",b in d)return"@"+a;for(var e=0;c>e;e++){var g=w[e];if(g.toUpperCase()+"_"+b in d)return"@-"+g.toLowerCase()+"-"+a}return!1};e.atRule=L;var Q=
e.testStyles=E,M={elem:h("modernizr")};d._q.push(function(){delete M.elem});var q={style:M.elem.style};d._q.unshift(function(){delete q.style});e.testAllProps=y;var u=e.prefixed=function(a,b,c){return 0===a.indexOf("@")?L(a):(-1!=a.indexOf("-")&&(a=D(a)),b?y(a,b,c):y(a,"pfx"))};d.addTest("fullscreen",!(!u("exitFullscreen",g,!1)&&!u("cancelFullScreen",g,!1)));d.addTest("requestanimationframe",!!u("requestAnimationFrame",f),{aliases:["raf"]});e.testAllProps=t;d.addTest("cssanimations",t("animationName",
"a",!0));d.addTest("backgroundsize",t("backgroundSize","100%",!0));d.addTest("bgsizecover",t("backgroundSize","cover"));d.addTest("csstransforms",function(){return-1===navigator.userAgent.indexOf("Android 2.")&&t("transform","scale(1)",!0)});d.addTest("csstransforms3d",function(){var a=!!t("perspective","1px",!0),b=d._config.usePrefixes;if(a&&(!b||"webkitPerspective"in m.style)){var c;d.supports?c="@supports (perspective: 1px)":(c="@media (transform-3d)",b&&(c+=",(-webkit-transform-3d)"));Q("#modernizr{width:0;height:0}"+
(c+"{#modernizr{width:7px;height:18px;margin:0;padding:0;border:0}}"),function(b){a=7===b.offsetWidth&&18===b.offsetHeight})}return a});d.addTest("csstransitions",t("transition","all",!0));(function(){var a,b,c,e,f,g;for(g in v)if(v.hasOwnProperty(g)){if(a=[],b=v[g],b.name&&(a.push(b.name.toLowerCase()),b.options&&b.options.aliases&&b.options.aliases.length))for(c=0;c<b.options.aliases.length;c++)a.push(b.options.aliases[c].toLowerCase());c=n(b.fn,"function")?b.fn():b.fn;for(e=0;e<a.length;e++)f=
a[e],f=f.split("."),1===f.length?d[f[0]]=c:(!d[f[0]]||d[f[0]]instanceof Boolean||(d[f[0]]=new Boolean(d[f[0]])),d[f[0]][f[1]]=c),J.push((c?"":"no-")+f.join("-"))}})();A(J);delete e.addTest;delete e.addAsyncTest;for(u=0;u<d._q.length;u++)d._q[u]();f.Modernizr=d}(window,document);
